version: '4.2'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017/db-node

  db:
    image: mongo:latest 
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data: